"use client";

import { FormEvent, useState } from "react";
import { Arrow } from "@/components/arrow";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

export default function ContactPage() {
  const [sent,setSent]=useState(false);
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSent(true);}
  return <main><SiteHeader /><section className="contact-hero"><div className="shell contact-page-grid"><div><p className="eyebrow light"><span /> Start a conversation</p><h1>Tell us what<br />you&apos;re <em>building.</em></h1><p>Hiring, looking for your next role or simply checking the market? You will speak directly with the specialist who owns your area.</p><div className="contact-cards"><a href="tel:0401904401"><span>Call</span><strong>0401 904 401</strong></a><a href="mailto:info@sajj.com.au"><span>Email</span><strong>info@sajj.com.au</strong></a><div><span>Hours</span><strong>10:00 – 18:00</strong></div></div></div><div className="contact-form-card">{sent?<div className="contact-success"><span>✓</span><h2>Thanks. We&apos;ll be in touch.</h2><p>Your message is ready for the right specialist desk.</p><button type="button" onClick={()=>setSent(false)}>Send another message</button></div>:<form onSubmit={submit}><div className="form-row"><label>First name<input required name="firstName" /></label><label>Last name<input required name="lastName" /></label></div><label>Email address<input required type="email" name="email" /></label><label>I&apos;m looking to<select name="reason" required defaultValue=""><option value="" disabled>Select one</option><option>Hire a specialist</option><option>Find my next role</option><option>Discuss contractor payroll</option><option>Ask a market question</option></select></label><label>Tell us a little more<textarea name="message" rows={5} placeholder="The role, project or next move..." /></label><button className="button button-white" type="submit">Send enquiry <Arrow /></button><p className="form-note">Your details stay with Sajj and are only used to respond to your enquiry.</p></form>}</div></div></section>
    <section className="inner-section"><div className="shell contact-reasons"><div><p className="eyebrow"><span /> Employers</p><h2>Need the shortlist, not the noise?</h2><p>Share the brief and we will connect you with the specialist consultant who owns that market.</p><a className="text-link" href="/services">Explore services <Arrow /></a></div><div><p className="eyebrow"><span /> Candidates</p><h2>Thinking about what comes next?</h2><p>Talk to a recruiter who understands your technical market and will represent you properly.</p><a className="text-link" href="/job-seekers">For job seekers <Arrow /></a></div></div></section><SiteFooter /></main>;
}
